Repository CEB2017/Gabot, pull requests merged in 2020-04, with the labels that each got.

#1 Beta release v0.1
  .gitignore
  Procfile
  app.py
  controllers/controllers.py
  controllers/db.py
  event/join.py
  event/message.py
  event/postback.py
  requirements.txt
  res/text/__init__.py
  res/text/greeting.py
  res/text/help.py
  res/text/member.py
  res/text/reminder.py
  res/text/schedule.py
  router/router.py
Labels: enhancement, good first issue, help wanted

#2 Documentation
  README.md
  pic/Delete schedule.jpg
  pic/Get schedule on specified day.jpg
  pic/Get schedule.jpg
  pic/Group reminder.jpg
  pic/List group reminder.jpg
  pic/NRP n fullname.jpg
  pic/Set schedule.jpg
  pic/Todo reminder.jpg
Labels: documentation

#3 Prevent Heroku from Idling
  app.py
Labels: bug

#4 Add sample for help command
  pic/Help-group.jpg
  pic/Help-personal.jpg
Labels: documentation

#5 Add exception handler, change route
  res/text/reminder.py
  res/text/schedule.py
  router/router.py
Labels: bug
